#!/usr/bin/env python3
"""Rare-table FX bake: tiles, ember glow map, star/coin points, caustics.

Outputs:
  assets/ui/table-rare-{ember,astronomer,vault}.jpg  (768 tiles)
  assets/ui/fx-ember-glow.png     (transparent warm-vein layer, breathes via CSS)
  assets/ui/fx-caustic-{a,b}.png  (procedural seamless caustic webs)
  js/tablefx-pts.js               (window.TABLEFX_PTS: tile-relative motif points)
Rerun after swapping any rare texture.
"""
import numpy as np, json
from PIL import Image, ImageFilter

def load_tile(path, size=768):
    im = Image.open(path).convert('RGB')
    w, h = im.size; s = min(w, h)
    return im.crop(((w-s)//2, (h-s)//2, (w+s)//2, (h+s)//2)).resize((size, size), Image.LANCZOS)

def bright_points(arr, warm_only, count=36, min_dist=48):
    lum = arr.mean(2)
    warm = (arr[:,:,0] > arr[:,:,2] + 10) if warm_only else np.ones(lum.shape, bool)
    score = np.where(warm, lum, 0)
    pts = []
    s = score.copy()
    for _ in range(count):
        i = int(np.argmax(s)); y, x = divmod(i, s.shape[1])
        if s[y, x] < np.percentile(score, 92): break
        pts.append((x / s.shape[1], y / s.shape[0]))
        y0,y1 = max(0,y-min_dist), y+min_dist; x0,x1 = max(0,x-min_dist), x+min_dist
        s[y0:y1, x0:x1] = 0
    return [(round(x,4), round(y,4)) for x,y in pts]

# ── Ember Throne ──
em = load_tile('/Users/admin/Downloads/rare-ember.png')
a = np.asarray(em).astype(np.float32)
a *= 0.94
Image.fromarray(np.clip(a,0,255).astype(np.uint8)).save('assets/ui/table-rare-ember.jpg','JPEG',quality=86,optimize=True)
# glow = warm bright veins only, feathered, on transparency
lum = a.mean(2); warm = (a[:,:,0] > a[:,:,2] + 18) & (lum > np.percentile(lum, 82))
mask = Image.fromarray((warm*255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(2))
glow = Image.merge('RGBA', (*Image.fromarray(np.clip(a*1.25,0,255).astype(np.uint8)).split(), mask))
glow.save('assets/ui/fx-ember-glow.png')

pts = {}
# ── Astronomer Royal ──
ast = load_tile('/Users/admin/Downloads/rare-astronomer.png')
a = np.asarray(ast).astype(np.float32) * 0.92
Image.fromarray(np.clip(a,0,255).astype(np.uint8)).save('assets/ui/table-rare-astronomer.jpg','JPEG',quality=86,optimize=True)
pts['rare-astronomer'] = bright_points(a, warm_only=True, count=34, min_dist=56)

# ── Drowned Vault ──
va = load_tile('/Users/admin/Downloads/rare-vault.png')
a = np.asarray(va).astype(np.float32)
med = np.median(a.reshape(-1,3), axis=0)
a = (a*0.78 + med*0.22) * 0.86          # mute the candy, deepen
Image.fromarray(np.clip(a,0,255).astype(np.uint8)).save('assets/ui/table-rare-vault.jpg','JPEG',quality=86,optimize=True)
pts['rare-vault'] = bright_points(a, warm_only=True, count=26, min_dist=64)

# ── procedural seamless caustics (wrapped-distance voronoi ridges) ──
def caustic(size, n, seed, blur=3):
    rng = np.random.RandomState(seed)
    p = rng.rand(n, 2) * size
    yy, xx = np.mgrid[0:size, 0:size].astype(np.float32)
    d = np.full((size, size), 1e9, np.float32); d2 = d.copy()
    for px, py in p:
        dx = np.abs(xx - px); dx = np.minimum(dx, size - dx)   # wrap = seamless
        dy = np.abs(yy - py); dy = np.minimum(dy, size - dy)
        dd = dx*dx + dy*dy
        closer = dd < d
        d2 = np.where(closer, d, np.minimum(d2, dd))
        d = np.where(closer, dd, d)
    ridge = 1 - np.clip((np.sqrt(d2) - np.sqrt(d)) / 18.0, 0, 1)
    ridge = (ridge ** 2.2 * 255).astype(np.uint8)
    img = Image.fromarray(ridge).filter(ImageFilter.GaussianBlur(blur))
    out = Image.merge('RGBA', (img.point(lambda v: 255), img.point(lambda v: 255), img.point(lambda v: 235), img))
    return out
caustic(640, 26, 7).save('assets/ui/fx-caustic-a.png')
caustic(640, 38, 23, blur=2).save('assets/ui/fx-caustic-b.png')

open('js/tablefx-pts.js','w').write(
    '// Generated by tools/bake-fx-points.py — motif anchors for tablefx.js\n'
    'window.TABLEFX_PTS = ' + json.dumps(pts) + ';\n')
print('baked:', {k: len(v) for k, v in pts.items()})
